### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jseppi** [jgrenon/angular-desktop-app#12]
Do you have a license in mind for this project?

**Comment by jgrenon** [comment]
Actually, I haven't thought about this. I would say that I would stick with the same license than angular or node-webkit uses. Node-webkit uses a Chromium / Intel license which seems derived from MIT or Apache. Angular uses MIT. So I may elect for the MIT license for this project.

**Comment by jseppi** [comment]
Cool, good to hear that!
As it stands now, however, the lack of a stated license precludes usage of
this project for some people for some types of work.
Great project btw!

**Comment by jgrenon** [comment]
I agree. I will add the license quickly.  
Thanks for the feedback!

**Comment by jseppi** [comment]
:+1:
