### ISSUE TITLE
Jade Templating

### ISSUE THREAD

**Issue by JProffitt71** [jgrenon/angular-desktop-app#14]
When using extends/include in Jade, the parser silently fails because it can't handle relative paths without passing the filename in options, resulting in a white screen.

I fixed this by modifying views.js and adding a path to each template, passed to the compile method:

``` javascript
            templates[f.substring(0, f.length - 5)] = {
                tmplfile:fs.readFileSync(path.resolve('./views', f)),
                tmplpath: path.resolve('./views', f),
                compiled:false
            };
...
                    tmpl.tmpl = jade.compile(tmpl.tmplfile, {'filename': tmpl.tmplpath});
```

**Comment by jgrenon** [comment]
I’ll review your code and integrate the solution into the master branch.  
Thanks for your help!
Joel

**Comment by jgrenon** [comment]
You improvement will be included in the next release. thanks
