### ISSUE TITLE
Gruntfile + grunt-node-webkit build script

### ISSUE THREAD

**Issue by talss89** [jgrenon/angular-desktop-app#7]
I've created a branch @ https://github.com/talss89/angular-desktop-app/tree/grunt

It's quite a major refactor in terms of the directory structure, but I think it's beneficial when managing release builds.

**Here are the changes:**
- Moved application code to src/
- Created a gruntfile
- Integrated with grunt-node-webkit-builder
- Removed client side LESS parser
- Added grunt-contrib-less support on run and build. src/css/app.less -> src/css/app.css
- Running `grunt clean` will delete contents of release dir
- Bumped node-webkit to 0.8.4
- Modified readme to include new setup / build instructions

**node-webkit is now automatically downloaded and installed for your specific system when `grunt install` is run.**

I have only tested this on a Windows (7) machine, but the logic is in the gruntfile for Mac + Linux. I've only run this through in my head. Please test if you can.

**Quickstart**
1. Clone https://github.com/talss89/angular-desktop-app/tree/grunt
2. Execute in project root `npm install && grunt install`
3. `grunt run` to fire it up

`grunt build` will create a production ready package in releases/ (or at least that's the idea)

Let me know what you think!

Tom.

**Comment by jgrenon** [comment]
thanks Tom. I agree, that’s a very good improvement.  
I’ll just review everything, test on mac and integrate your branch in the master.  
Joel

**Comment by jgrenon** [comment]
Tom,  

Everything was building and running perfectly on my mac. I’ve integrated your grunt branch into my master.  

Joel

**Comment by talss89** [comment]
Hi Joel,

Great, thanks for testing. I'll give Ubuntu a go soon too.

This is such a useful skeleton for me - thanks for making it available.

Tom.
